project:
  type: website
  output-dir: docs

website:
  favicon: images/randomfavicon.jpeg
  title: "Farhan (Adin) Aditya R."
  page-footer:
    left: "© 2026 Farhan Aditya Ramadhan · Economics · Policy · Data"
    right: 
      - icon: linkedin
        href: "https://www.linkedin.com/in/adinramaadin/"
      - icon: github
        href: "https://github.com/farhanadityaramadhan"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "Overview"
      - about.qmd
      - text: "Projects"
        menu:
          - webpages/projects/analysis.qmd
          - webpages/projects/research.qmd
          - webpages/projects/blog.qmd
      # - sidebar:resources
    right:
      - href: index.qmd
        text: " "
        icon: house-door-fill
      - href: "https://www.linkedin.com/in/adinramaadin/"
        text: " "
        icon: linkedin
      - href: "https://github.com/farhanadityaramadhan"
        text: " "
        icon: github
  # sidebar: 
  #   - id: resources
  #     title: "Resources"
  #     style: "docked"
  #     background: light
  #     collapse-level: 1
  #     contents: 
  #       -
  #       -

    
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



